---
# tasks file for connect_to_repository

- name: Set cmd regarding the type repository
  ansible.builtin.include_role:
    name: setup_repo_cmd

- block:
    - name: Check auth status
      shell: "{{ CMD }} auth status"
      register: auth_status

    - debug:
        var: auth_status['stdout']

  rescue:
    - debug:
        msg: |
          # Run manually command: "{{ CMD }} auth login {{ RIGHTS }}"
          #
          # Then relaunch your command...
