---
# tasks file for connect_to_repository

- name: Set cmd regarding the type repository
  ansible.builtin.include_role:
    name: setup_repo_cmd

- name: Block connect repo
  block:
    - name: Check auth status
      ansible.builtin.shell: "{{ cmd }} auth status"
      register: auth_status
      changed_when: false

    - name: Debug
      ansible.builtin.debug:
        var: auth_status['stdout']

  rescue:
    - name: Debug
      ansible.builtin.debug:
        msg: |
          # Run manually command: "{{ cmd }} auth login {{ rights }}"
          #
          # Then relaunch your command...
