#!/bin/bash

echo '```'                      >  help
just -f ../../justfile _help    >> help
echo '```'                      >> help

sed -i -n \
  -e "1,/<\!-- Autogenerated -->/ p" \
  -e"/<\!-- END -->/,$ p" \
  -e "/<\!-- Autogenerated -->/ r help" \
../../README.md

rm -f help