---
- name: Get your current ansible version # noqa: command-instead-of-module
  ansible.builtin.shell: set -o pipefail && ansible --version | head -1 | awk '{sub(/]/,"");print $NF}'
  args:
    executable: /bin/bash
  register: version
  changed_when: false

- name: Set ansible_current_version
  ansible.builtin.set_fact:
    ansible_current_version: "{{ version['stdout'] }}"

- name: Initialize a new Collection
  ansible.builtin.command: "ansible-galaxy collection init {{ collection_namespace }}.{{ collection_name }} --init-path ~/"
  args:
    creates: "~/{{ collection_namespace }}/{{ collection_name }}"

- name: Create complementary directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'directory'
    recurse: true
  loop:
    - '~/{{ collection_namespace }}/{{ collection_name }}/plugins/filter'
    - '~/{{ collection_namespace }}/{{ collection_name }}/plugins/modules'
    - '~/{{ collection_namespace }}/{{ collection_name }}/plugins/inventory'
    - '~/{{ collection_namespace }}/{{ collection_name }}/playbooks/files'
    - '~/{{ collection_namespace }}/{{ collection_name }}/playbooks/vars'
    - '~/{{ collection_namespace }}/{{ collection_name }}/playbooks/templates'
    - '~/{{ collection_namespace }}/{{ collection_name }}/playbooks/tasks'
    - '~/{{ collection_namespace }}/{{ collection_name }}/scripts/prerequis'
    - '~/{{ collection_namespace }}/{{ collection_name }}/meta/'

- name: Push templates inside collection
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: u=rw,g=r,o=r
  loop:
    - { src: 'plugins/inventory/hosts.yml',                dest: '~/{{ collection_namespace }}/{{ collection_name }}/plugins/inventory/hosts.yml' }
    - { src: 'collections/pre-commit-config.yaml',         dest: '~/{{ collection_namespace }}/{{ collection_name }}/.pre-commit-config.yaml' }
    - { src: 'collections/ansible_lint',                   dest: '~/{{ collection_namespace }}/{{ collection_name }}/.ansible_lint' }
    - { src: 'collections/yamllint',                       dest: '~/{{ collection_namespace }}/{{ collection_name }}/.yamllint' }
    - { src: 'collections/gitignore',                      dest: '~/{{ collection_namespace }}/{{ collection_name }}/.gitignore' }
    - { src: 'collections/ansible.cfg',                    dest: '~/{{ collection_namespace }}/{{ collection_name }}/ansible.cfg' }
    - { src: 'collections/CHANGELOG.md',                   dest: '~/{{ collection_namespace }}/{{ collection_name }}/CHANGELOG.md' }
    - { src: 'collections/galaxy.yml.j2',                  dest: '~/{{ collection_namespace }}/{{ collection_name }}/galaxy.yml' }
    - { src: 'collections/{{ collection_licence_file }}',  dest: '~/{{ collection_namespace }}/{{ collection_name }}/LICENSE' }
    - { src: 'collections/Makefile',                       dest: '~/{{ collection_namespace }}/{{ collection_name }}/Makefile' }
    - { src: 'collections/README.md.j2',                   dest: '~/{{ collection_namespace }}/{{ collection_name }}/README.md' }
    - { src: 'collections/meta/runtime.yml.j2',            dest: '~/{{ collection_namespace }}/{{ collection_name }}/meta/runtime.yml' }
    - { src: 'collections/meta/execution-environment.yml', dest: '~/{{ collection_namespace }}/{{ collection_name }}/meta/execution-environment.yml' }
    - { src: 'collections/meta/ee-arkade.txt',             dest: '~/{{ collection_namespace }}/{{ collection_name }}/meta/ee-arkade.txt' }
    - { src: 'collections/meta/ee-bindeps.txt',             dest: '~/{{ collection_namespace }}/{{ collection_name }}/meta/ee-bindeps.txt' }
    - { src: 'collections/meta/ee-images.txt',             dest: '~/{{ collection_namespace }}/{{ collection_name }}/meta/ee-images.txt' }
    - { src: 'collections/meta/ee-requirements.txt',       dest: '~/{{ collection_namespace }}/{{ collection_name }}/meta/ee-requirements.txt' }
    - { src: 'collections/meta/ee-requirements.yml',       dest: '~/{{ collection_namespace }}/{{ collection_name }}/meta/ee-requirements.yml' }

- name: Push files inside collection
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: u=rw,g=r,o=r
  loop:
    - { src: 'playbooks/ping.yml',                         dest: '~/{{ collection_namespace }}/{{ collection_name }}/playbooks/tasks/ping.yml' }
    - { src: 'playbooks/test.yml',                         dest: '~/{{ collection_namespace }}/{{ collection_name }}/playbooks/tasks/test.yml' }
    - { src: 'scripts/prerequis/arkade.sh',                dest: '~/{{ collection_namespace }}/{{ collection_name }}/scripts/prerequis/arkade.sh' }
    - { src: 'scripts/prerequis/podman-load.sh',           dest: '~/{{ collection_namespace }}/{{ collection_name }}/scripts/prerequis/podman-load.sh' }
    - { src: 'scripts/prerequis/Makefile',                 dest: '~/{{ collection_namespace }}/{{ collection_name }}/scripts/prerequis/Makefile' }
