---

- name: Initialize a new Collection
  command: "ansible-galaxy collection init {{ collection_namespace }}.{{ collection_name }} --init-path ~/"
  args: 
    creates: "~/{{ collection_namespace }}/{{ collection_name }}"

- name: Create complementary directories
  file: 
    path: '{{ item }}'
    state: 'directory'
    recurse: true
  loop:
    - '~/{{ collection_namespace }}/{{ collection_name }}/plugins/filter'
    - '~/{{ collection_namespace }}/{{ collection_name }}/plugins/modules'
    - '~/{{ collection_namespace }}/{{ collection_name }}/plugins/inventory'
    - '~/{{ collection_namespace }}/{{ collection_name }}/playbooks/files'      
    - '~/{{ collection_namespace }}/{{ collection_name }}/playbooks/vars'
    - '~/{{ collection_namespace }}/{{ collection_name }}/playbooks/templates'
    - '~/{{ collection_namespace }}/{{ collection_name }}/playbooks/tasks'
    - '~/{{ collection_namespace }}/{{ collection_name }}/scripts/prerequis'
    - '~/{{ collection_namespace }}/{{ collection_name }}/deps'

- name: Push templates inside collection
  template: 
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: 'plugins/inventory/hosts.yml',                dest: '~/{{ collection_namespace }}/{{ collection_name }}/plugins/inventory/hosts.yml' }
    - { src: 'collections/pre-commit-config.yaml',         dest: '~/{{ collection_namespace }}/{{ collection_name }}/.pre-commit-config.yaml' } 
    - { src: 'collections/ansible_lint',                   dest: '~/{{ collection_namespace }}/{{ collection_name }}/.ansible_lint' }
    - { src: 'collections/yamllint',                       dest: '~/{{ collection_namespace }}/{{ collection_name }}/.yamllint' }
    - { src: 'collections/gitignore',                      dest: '~/{{ collection_namespace }}/{{ collection_name }}/.gitignore' }
    - { src: 'collections/ansible.cfg',                    dest: '~/{{ collection_namespace }}/{{ collection_name }}/ansible.cfg' }
    - { src: 'collections/changelog.md',                   dest: '~/{{ collection_namespace }}/{{ collection_name }}/changelog.md' }
    - { src: 'collections/galaxy.yml.j2',                  dest: '~/{{ collection_namespace }}/{{ collection_name }}/galaxy.yml' }
    - { src: 'collections/{{ collection_licence_file }}',  dest: '~/{{ collection_namespace }}/{{ collection_name }}/LICENSE' }
    - { src: 'collections/Makefile',                       dest: '~/{{ collection_namespace }}/{{ collection_name }}/Makefile' }
    - { src: 'collections/README.md.j2',                   dest: '~/{{ collection_namespace }}/{{ collection_name }}/README.md' } 

- name: Push files inside collection
  copy: 
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: 'playbooks/ping.yml',                         dest: '~/{{ collection_namespace }}/{{ collection_name }}/playbooks/tasks/ping.yml' }
    - { src: 'playbooks/test.yml',                         dest: '~/{{ collection_namespace }}/{{ collection_name }}/playbooks/tasks/test.yml' }
    - { src: 'scripts/prerequis/arkade.sh',                dest: '~/{{ collection_namespace }}/{{ collection_name }}/scripts/prerequis/arkade.sh' }
    - { src: 'scripts/prerequis/load.sh',                  dest: '~/{{ collection_namespace }}/{{ collection_name }}/scripts/prerequis/load.sh' }
    - { src: 'scripts/prerequis/Makefile',                 dest: '~/{{ collection_namespace }}/{{ collection_name }}/scripts/prerequis/Makefile' }
    - { src: 'deps/arkade.txt',                            dest: '~/{{ collection_namespace }}/{{ collection_name }}/deps/arkade.txt' }
    - { src: 'deps/bindep.txt',                            dest: '~/{{ collection_namespace }}/{{ collection_name }}/deps/bindep.txt' }
    - { src: 'deps/images.txt',                            dest: '~/{{ collection_namespace }}/{{ collection_name }}/deps/images.txt' }
    - { src: 'deps/requirements.txt',                      dest: '~/{{ collection_namespace }}/{{ collection_name }}/deps/requirements.txt' }
    - { src: 'deps/requirements.yml',                      dest: '~/{{ collection_namespace }}/{{ collection_name }}/deps/requirements.yml' }