---
# defaults file for createCollection
collection_name: "{{ global_collection_name }}"
collection_namespace: "{{ global_collection_namespace }}"
collection_repository_https: "{{ 'https://' + global_target_repository if global_target_repository | length > 0 else '~' }}"

project_path:           "~/{{ collection_namespace }}/{{ collection_name }}"

collection_author_email: "{{ global_author_email | default('') }}"
collection_version: "{{ global_collection_version | default('1.0.0') }}"
collection_description: "{{ global_collection_description | default('') }}"
collection_licence_spdx: "{{ global_licence_spdx | default('Apache-2.0') }}"
collection_licence_file: "LICENSE_{{ collection_licence_spdx }}"