name: Update AnsiColt Readme
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update AnsiColt Readme

    steps:
      - uses: actions/checkout@v4

      - name: Install Arkade
        run: |
          LATEST_VERSION_URL="https://api.github.com/repos/alexellis/arkade/releases/latest"
          LATEST_VERSION=$(curl -s "${LATEST_VERSION_URL}" | grep '"tag_name":' | cut -d'"' -f4)
          DOWNLOAD_URL="https://github.com/alexellis/arkade/releases/download"
          curl -LO "${DOWNLOAD_URL}"/"${LATEST_VERSION}"/arkade > /dev/null 2>&1
          chmod +x arkade 
          mkdir -p  $HOME/.arkade/bin/
          sudo mv arkade $HOME/.arkade/bin/
          export PATH=$PATH:$HOME/.arkade/bin/
          ls -l $HOME/.arkade/bin/
          just --help

      - name: Install Just Commandliner
        run: |
          arkade get just

      - name: Get justfile help
        run: |
          JUSTFILE_HELP=$(just)

      - uses: Readme-Workflows/readme-replacer@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Those are all default values and only are shown for demonstration
          TEMPLATE_FILE: './.github/TEMPLATE.md'
          COMMIT_FILE: './.github/README.md'
          CUSTOM_REPLACER_FILE: './.github/customReplacer.json'