name: Update AnsiColt Readme
on:
  push:

jobs:
  readme:
    runs-on: ubuntu-latest
    name: Update AnsiColt Readme
    
    if: github.repository == 'mozebaltyk/ansicolt'
    permissions:
      actions: write
      checks: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update Readme
        run: |
          LATEST_VERSION_URL="https://api.github.com/repos/alexellis/arkade/releases/latest"
          LATEST_VERSION=$(curl -s "${LATEST_VERSION_URL}" | grep '"tag_name":' | cut -d'"' -f4)
          DOWNLOAD_URL="https://github.com/alexellis/arkade/releases/download"
          curl -LO "${DOWNLOAD_URL}"/"${LATEST_VERSION}"/arkade > /dev/null 2>&1
          chmod +x arkade 
          mkdir -p  $HOME/.arkade/bin/
          sudo mv arkade $HOME/.arkade/bin/
          export PATH=$PATH:$HOME/.arkade/bin/
          arkade version
          arkade get just
          just --version
          cd scripts/docs/ && sh -c "./autogenerate_README.sh" && cat ../../README.md

      - name: Git push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push origin