name: Update AnsiColt Readme
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update AnsiColt Readme

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          wget -qO - 'https://proget.makedeb.org/debian-feeds/makedeb.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/makedeb-archive-keyring.gpg 1> /dev/null
          echo 'deb [signed-by=/usr/share/keyrings/makedeb-archive-keyring.gpg arch=all] https://proget.makedeb.org/ makedeb main' | sudo tee /etc/apt/sources.list.d/makedeb.list
          sudo apt update
          sudo apt install makedeb
          git clone 'https://mpr.makedeb.org/just'
          cd just
          makedeb -si
          sudo apt install just
          JUSTFILE_HELP=$(just)

      - uses: Readme-Workflows/readme-replacer@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Those are all default values and only are shown for demonstration
          TEMPLATE_FILE: './.github/TEMPLATE.md'
          COMMIT_FILE: './.github/README.md'
          CUSTOM_REPLACER_FILE: './.github/customReplacer.json'