name: Update AnsiColt Readme
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update AnsiColt Readme

    steps:
      - uses: actions/checkout@v4

      - name: Get Justfile Help
        id: get_justfile_help
        run: |
          LATEST_VERSION_URL="https://api.github.com/repos/alexellis/arkade/releases/latest"
          LATEST_VERSION=$(curl -s "${LATEST_VERSION_URL}" | grep '"tag_name":' | cut -d'"' -f4)
          DOWNLOAD_URL="https://github.com/alexellis/arkade/releases/download"
          curl -LO "${DOWNLOAD_URL}"/"${LATEST_VERSION}"/arkade > /dev/null 2>&1
          chmod +x arkade 
          mkdir -p  $HOME/.arkade/bin/
          sudo mv arkade $HOME/.arkade/bin/
          export PATH=$PATH:$HOME/.arkade/bin/
          arkade version
          arkade get just
          just --version

      - name: Update Readme
        run: |
          cd ./scripts/docs/
          ./autogenerate_README.sh
          cat README.md

      #echo "::set-output name=JUSTFILE_HELP::$(just)"

      #- uses: Readme-Workflows/readme-replacer@v1.0.1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    JUSTFILE_HELP: ${{ steps.get_justfile_help.outputs.JUSTFILE_HELP }}
      #  with:
      #    # Those are all default values and only are shown for demonstration
      #    TEMPLATE_FILE: './.github/TEMPLATE.md'
      #    COMMIT_FILE: './.github/README.md'
      #    CUSTOM_REPLACER_FILE: './.github/customReplacer.json'